### ISSUE TITLE
Tests fail on cloned repository, even after running "npm install"

### ISSUE THREAD

**Issue by TehShrike** [getify/asynquence#54]
contrib.src.js doesn't exist in any directory, and the following line trying to load asq.js fails as well (unless you run build first, which I didn't figure should be necessary).

Tested on OSX on node 0.10.32:

```
...
Core Test #23: PASSED
Core Test #24: PASSED
ALL CORE TESTS PASSED!


module.js:340
    throw err;
          ^
Error: Cannot find module '/Users/josh/code/asynquence/contrib/contrib.src.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/josh/code/asynquence/contrib/node-tests.js:14:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
*** TEST SUITE FAILURE ***
```

**Comment by legodude17** [comment]
The problem is that `npm install`. Will not build the contrib, and the built contrib is required for the tests. My PR will make this easier: #91

**Comment by getify** [comment]
Again, you shouldn't be running "npm *" commands unless you retrieved the code from npm. There's bound to be mismatches when doing so.

**Comment by TehShrike** [comment]
What?  I must be misunderstanding you.  `git clone repository; npm install` seems to be standard setup/test process in the node/JavaScript community.  Are you saying that you don't expect anybody to be doing that?

What is the setup/test process that you expect contributors to follow?

**Comment by getify** [comment]
Maybe that is a "standard". But it's never been something I did, not even once. So no, I didn't design or structure the repo and packages that way.

If you want to `git clone` + `npm *`, then you need to remember that this git repo actually includes **two separate npm package roots** in it. So, roughly, I think you would need to do `npm install` in the root of this repo, and **also** `npm install` in the contrib/ dir. IIUC, that should build both the core and the contrib.

I know that `npm install` doesn't have the precedent to recursively run in subdirectories, b/c it's probably not common to have a git repo with two npm package roots in it.

Keep in mind that if you get *asynquence* from npm, you only get the core... there's no subdir for the contrib package. So through npm usage, you end up with *asynquence* and *asynquence-contrib* as side-by-side node_modules directories, not the latter inside the former.

I don't want to make the use-case of getting-and-using-from-npm awkward or difficult. So the package.json setup is designed to support that, primarily. If you go the git route, that's fine, but it works differently, and requires a little more work.

**Comment by TehShrike** [comment]
So if someone wanted to be able to run the tests from git and be able to contribute pull requests to the Github repo, what process should they follow?

**Comment by getify** [comment]
I think I would advise following this:

1. `git clone ..`
2. in /, `npm install`
3. in contrib/, `npm install`
4. ...

Is there something about that I'm missing which makes it not work? I was under the impression that the complaint is that the first `npm install` doesn't automatically do the second one, which I've tried to explain why.

**Comment by TehShrike** [comment]
Yeah, the issue is that I never knew that I had to do the step where you navigate to `contrib` and run `npm install`  - it wasn't in the readme, and I wasn't able to derive that extra step from the scripts.  I think if you add a "How to contribute" section to the readme then you'll be covered.

As long as "how to contribute/develop" is in the readme, I don't care how many `npm install`s are in it.

**Comment by getify** [comment]
Nods. Yeah that was my original plan i just haven't gotten around to it. Good reminder tho. :)

**Comment by legodude17** [comment]
Something that would be very helpful is some sort of task file with one of
many different task managers.

**Comment by legodude17** [comment]
There should be a contribution section: #93. I can do that once we agree on the best way to lay it out.

**Comment by legodude17** [comment]
Another option would be like a build all type file, like `build-all.js` that would run `npm install` in both. And then it could be added to `.npmignore`.

**Comment by getify** [comment]
Yeah, that might work. Wouldn't be an npm script, so people would have to run it manually.

**Comment by legodude17** [comment]
I will look into it.

**Comment by legodude17** [comment]
Finished: #94.
