### ISSUE TITLE
Investigate: long stack traces support

### ISSUE THREAD

**Issue by getify** [getify/asynquence#57]

**Comment by legodude17** [comment]
Why do you mean by long stack traces?

**Comment by getify** [comment]
check out bluebird's "long stack traces". It has to do with being able to trace/inspect the entire async stack of operations that preceded an error.

**Comment by legodude17** [comment]
Ah, so something like what bluebird does, just put into asynquence.

**Comment by legodude17** [comment]
Early investigation shows that bluebird and when do this, and it would be at least 150 lines, probably around 250 - 300.

**Comment by getify** [comment]
Thank you for the estimates. I am partially concerned about "cost" (file size, perf) and partially concerned about the best way to configure it (per chain) -- default on or off? -- and also concerned about the best way to make the stack trace available. lots to think about.

**Comment by legodude17** [comment]
The cost is quite big. One way is to have it on according to environment variables. You could also add a `ASQ.config` function.

**Comment by getify** [comment]
Want this to work in browser too. So no on env vars. Should also investigate if there are other things that should be configurable per instance and if so, make sure we expose this config consistently.

**Comment by legodude17** [comment]
I now think the best way to do this would be to just provide a platform so that a monitor and reporter can be built in separate files. This will also allow people to make thier own monitoring functionality. This is what `when` does.

**Comment by getify** [comment]
Do you have any links to read more about this?

**Comment by getify** [comment]
Perhaps a way to specify a listener on a sequence that is notified for each step, so someone else could hook into that from the outside and listen to an entire sequence, whether it's error or not.

**Comment by legodude17** [comment]
I got this from reading when's code. Relevant files:
+ [PromiseMonitor](https://github.com/cujojs/when/blob/master/monitor/PromiseMonitor.js)
+ [ConsoleReporter](https://github.com/cujojs/when/blob/master/monitor/ConsoleReporter.js)
+ [makePromise](https://github.com/cujojs/when/blob/master/lib/makePromise.js)
The main limit to doing this as a plugin is that plugins can't listen for events. Maybe we could add that?

**Comment by legodude17** [comment]
Basics are done now:
Output without long trace:
```
Error: Ahhh!
    at Timeout.$$timeout [as _onTimeout] (/home/jdb/Desktop/Code/ASQDev/asynquence/test-long-trace.js:9:45)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)

```
Output with lone trace:
```
Error: Ahhh!
    at Timeout.$$timeout [as _onTimeout] (/home/jdb/Desktop/Code/ASQDev/asynquence/test-long-trace.js:9:45)
    at Object.<anonymous> (/home/jdb/Desktop/Code/ASQDev/asynquence/test-long-trace.js:5:1)
```

With this code:
```js
var ASQ = require("./contrib/contrib.src.js");
try { ASQ.messages(); } catch (err) {
	ASQ = ASQ( require("./asq.src.js") );
}
ASQ().then(function $$handle(done) {
	setTimeout(function () {ASQ().then(handle).pipe(done); }, 100);
});
function handle(done) {
	setTimeout(function $$timeout() {done.fail(new Error('Ahhh!'))}, 100);
}
```

**Comment by legodude17** [comment]
The method to do this adds 27 unminified lines to `asq.src.js` and adds a 153 line plugin in contrib.
